[package]
name = "nexus-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
bincode = { workspace = true }
nexus-common = { path = "../nexus-common" }